version: '3.3'

services:
  app:
    build: .
    ports:
      - 8080:25000
    environment:
      - DB_USER=DB_USER
      - DB_PASSWORD=DB_PASSWORD
      - DB_NAME=DB_NAME
      - DB_HOST=db
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=DB_PASSWORD
      - POSTGRES_USER=DB_USER
      - POSTGRES_DB=DB_NAME